# Generated by Django 5.1.2 on 2024-10-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturing_year', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=250)),
                ('available', models.BooleanField(default=True)),
                ('mileage', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_capacity', models.IntegerField(default=4)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('current_status', models.CharField(default='Available', max_length=50)),
                ('last_serviced_date', models.DateField(blank=True, null=True)),
                ('insurance_included', models.BooleanField(default=False)),
                ('extras', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('cars', models.ManyToManyField(blank=True, related_name='service', to='car_management.car')),
            ],
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('cars', models.ManyToManyField(blank=True, related_name='tour_package', to='car_management.car')),
            ],
        ),
    ]
