# Generated by Django 5.1.2 on 2024-12-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_management', '0004_tourbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Minivan', 'Minivan'), ('Microcar', 'Microcar'), ('Convertible', 'Convertible')], default=None, max_length=50, null=True),
        ),
    ]
